resources:
  repositories:
    - repository: wikiRepo
      type: git
      name: Fusee/Fusee.wiki
      trigger: none

jobs:
- job: SyncWikiToGitHub
  displayName: "Synchroniser le Wiki Azure DevOps avec le Wiki GitHub"
  steps:
    - checkout: wikiRepo

    - script: |
        git config --global user.email "wiki-bot@csf-dfc.ca"
        git config --global user.name "Azure DevOps"

        mkdir temp-wiki
        rsync -av --exclude='.git' ./ temp-wiki/

        cd temp-wiki
        git init
        git checkout -b master
        git remote add origin https://$(GitHubPAT)@github.com/BlueScreen-AeroSpace/DIY_Water_Propeled_Rocket_Fusee_a_Eau.wiki.git
        git add .
        git commit -m "Sync du wiki Azure vers GitHub Wiki"
        git push origin master --force
      env:
        GitHubPAT: $(GitHubPAT)
      displayName: "Pousser tous les fichiers vers GitHub Wiki (force push)"